grados/app/accounts/urls.py
from django.urls import path

from grados.app.views import accounts

app_name = "accounts"

urlpatterns = [
    path("login", accounts.AccountTemplateView.as_view(), name="accounts_login"),
    path("logout", accounts.AccountLogoutView.as_view(), name="accounts_logout"),
    path("dashboard", accounts.DashboardTemplateView.as_view(), name="dashboard_view"),
]

grados/app/parents/urls.py
from django.urls import path

from grados.app.views import parents

app_name = "parents"

urlpatterns = [
    path("", parents.ParentTemplateView.as_view(), name="parents_index"),
    path("add/", parents.ParentCreateView.as_view(), name="parents_add"),
]

grados/app/students/urls.py
from django.urls import path

from grados.app.views import students

app_name = "students"


urlpatterns = [
    path("index/", students.StudentsTemplateView.as_view(), name="students_index"),
    path("add/", students.StudentCreateView.as_view(), name="student_add"),
]

grados/app/teachers/urls.py
from django.urls import path

from grados.app.views import teachers

app_name = "teachers"

urlpatterns = [
    path("index/", teachers.TeachersTemplateView.as_view(), name="teachers_index"),
    path("add/", teachers.TeacherCreateView.as_view(), name="teachers_add"),
]

grados/configs/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("teacher/", include("grados.app.teachers.urls")),
    path("accounts/", include("grados.app.accounts.urls")),
    path("students/", include("grados.app.students.urls")),
    path("parents/", include("grados.app.parents.urls")),
    path("__debug__", include(debug_toolbar.urls)),  # Debug purposes
]

grados/app/accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils.translation import gettext as _

from grados.app.core.models import GradoTimeStampModel


class CustomUserManager(UserManager):
    pass  # check if whats the use of UserManager


class CustomUser(AbstractUser):
    object = CustomUserManager()

    @property
    def get_user_account_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def get_user_email(self):
        return self.email


class Role(models.Model, GradoTimeStampModel):
    class Meta:
        abstract = True

    ROLE_NAME = (
        ("Admin", "Administrator"),
        ("Parents", "Parents"),
        ("Teacher", "Teacher"),
        ("Editor", "Editor"),
        ("Approver", "Approver"),
    )

    role_name = models.CharField(
        max_length=200, choices=ROLE_NAME, blank=False, verbose_name=_("Role Name")
    )

    role_desc = models.CharField(
        max_length=200,
        verbose_name=_("Role Description"),
        blank=False,
    )

    role_mapping_id = models.CharField(
        max_length=200, verbose_name=_("Role Mapping"), blank=False
    )

    role_hash = models.CharField(
        max_length=200, verbose_name=_("Role Hash"), blank=False
    )

grados/app/class/models.py
from django.db import models
from django.utils.translation import gettext as _

from grados.app.accounts.models import CustomUser
from grados.app.core.models import TimeStampModel

# Create your models here.


class StudentClass(models.Model, TimeStampModel):
    class_name = models.CharField(
        max_length=200, verbose_name=_("Name of Class"), blank=False
    )

    class_sched = models.DateTimeField(verbose_name=_("Schedule of class"))

    class_desc = models.CharField(
        max_length=200, verbose_name=_("Description of Class")
    )

    max_students_enrolled = models.CharField(
        max_length=200,
        verbose_name=_("Students Enrolled in Class"),
        blank=False,
    )

    class_status = models.CharField(
        max_length=200, verbose_name=_("Status of Class"), blank=False
    )
    # TODO: Add logic for step wizard when dealing the approved and editing of a student class
    approved_by = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name=_("Approved By"),
    )

    updated_by = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, verbose_name=_("Updated By")
    )

    class Meta:
        db_table = _("student_class")
        verbose_name = _("Students Class")
        verbose_name_plural = _("Student Classes")
        ordering = ["id"]

grados/app/core/models.py
from django.db import models
from django.utils.translation import gettext as _


class GradoTimeStampModel(models.DateTimeField):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created At"))

    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated At"))


class GradoBasicInfo(models.Model):
    class Meta:
        abstract = True

    first_name = models.CharField(
        max_length=200, verbose_name=_("First Name"), blank=False
    )

    last_name = models.CharField(
        max_length=200, verbose_name=_("Last Name"), blank=False
    )

    middle_name = models.CharField(
        max_length=200, verbose_name=_("Middle Name"), blank=False
    )


class GradoAddressInfo(models.Model):
    class Meta:
        abstract = True

    address1 = models.CharField(
        max_length=200, verbose_name=_("Address 1"), blank=False
    )

    address2 = models.CharField(
        max_length=200, verbose_name=_("Address 2"), blank=False
    )

grados/app/parents/models.py
from django.db import models
from django.utils.translation import gettext as _

from grados.app.core.models import GradoAddressInfo, GradoBasicInfo, GradoTimeStampModel
from grados.app.students.models import Student


class Parent(GradoBasicInfo, GradoAddressInfo, GradoTimeStampModel):
    student_id = models.ForeignKey(
        Student, on_delete=models.CASCADE, verbose_name=_("Students")
    )

    occupation = models.CharField(
        max_length=200, verbose_name=_("Occupation"), blank=False
    )

    tel_number = models.CharField(
        max_length=20, verbose_name=_("Telephone Number"), blank=True
    )

    phone_number = models.CharField(
        max_length=20, verbose_name=_("Phone Number"), blank=True
    )

    email_address = models.EmailField(
        max_length=200, verbose_name=_("Email Address"), blank=False
    )
    # TODO: Check if this field is need to be Boolean Field
    # TODO: What will be the design if the user will pick No as Legal Guardian
    legal_guardian = models.BooleanField(
        max_length=10, verbose_name=_("Legal Guardian"), blank=False
    )

    class Meta:
        db_table = _("parents")
        verbose_name = _("Parent")
        verbose_name_plural = _("Parents")
        ordering = ["id"]

    def __str__(self):
        return f"{self.parent_firstname} {self.parent_lastname}"

grados/app/students/models.py
from django.db import models
from django.utils.translation import gettext as _

from grados.app.core.models import GradoBasicInfo, GradoTimeStampModel
from grados.app.teachers.models import Teacher


# TODO: Create normalize table for students and teacher
class Student(GradoBasicInfo, GradoTimeStampModel):
    teacher_id = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, verbose_name=_("Students")
    )

    age = models.SmallIntegerField(verbose_name=_("Age"), blank=False)

    class Meta:
        db_table = _("students")
        verbose_name = _("Student")
        verbose_name_plural = _("Students")
        ordering = ["id"]

    def __str__(self):
        return f"{self.stud_firstname} {self.stud_lastname}"

grados/app/teachers/models.py
from django.db import models
from django.utils.translation import gettext as _

from grados.app.accounts.models import CustomUser
from grados.app.core.models import GradoAddressInfo, GradoTimeStampModel


class Teacher(AddressInfo, TimeStampModel):
    LIFE_DESIGNATION = (("mr.", "Mr."), ("mrs.", "Mrs."), ("ms.", "Miss"))

    teacher_accounts_id = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, verbose_name=_("Teacher Acccount")
    )

    birth_date = models.DateField(
        verbose_name=_("Birth Date"),
    )

    designation_as = models.CharField(
        choices=LIFE_DESIGNATION,
        max_length=50,
        verbose_name=_("Designation As."),
    )

    profile_pic_id = models.CharField(
        max_length=50, verbose_name=_("Upload profile picture"), blank=False
    )

    role_of_work = models.CharField(
        max_length=200, verbose_name=_("Role of Work"), blank=False
    )

    teacher_status = models.CharField(
        max_length=200, verbose_name=_("Status of Teacher"), blank=False
    )

    class Meta:
        db_table = _("teachers")
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")
        ordering = ["id"]

    def __str__(self):
        return f"{self.birth_date}"

grados/app/forms/accountsForm.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext as _

class CustomAuthenticationForm(AuthenticationForm):
	error_messages = {
		"invalid_login": "Username and Password doesnt recognize by the system",
		"inactive": "Permission denied",
	}
	# BUG: when submitting the form non field error resetting the form
	def __init__(self, *args, **kwargs):	
		super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
		self.fields['username'].error_messages = {'required': "Username is required field"}
		self.fields['password'].error_messages = {'required': "Password is required field"}

grados/app/forms/form.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext as _

from grados.app.parents.models import Parent
from grados.app.students.models import Student
from grados.app.teachers.models import Teacher
from grados.configs.settings.grados_settings import MAX_AGE_LIMIT


class FormsForm(forms.ModelForm):
    """
    Base form class that will be use to add global functionality
    of the ModelForm classes
    """

    pass


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        "invalid_login": "Username and Password doesnt recognize by the system",
        "inactive": "Permission denied",
    }

    # BUG: when submitting the form non field error resetting the form
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields["username"].error_messages = {
            "required": "Username is required field"
        }
        self.fields["password"].error_messages = {
            "required": "Password is required field"
        }


class TeacherForms(FormsForm):
    class Meta:
        verbose_name = _("Teacher Form")
        verbose_plural_name = _("Teachers Forms")
        model = Teacher
        fields = [
            "address1",
            "address2",
            "birth_date",
            "designation_as",
            "role_of_work",
            "teacher_status",
            "profile_pic_id",
        ]
        ordering = ["-id"]


class ParentForms(FormsForm):
    class Meta:
        verbose_name = _("Parent Form")
        verbose_plural_name = _("Parents Forms")
        model = Parent
        fields = [
            "student_id",
            "first_name",
            "last_name",
            "middle_name",
            "occupation",
            "address1",
            "address2",
            "tel_number",
            "phone_number",
            "email_address",
            "legal_guardian",
        ]
        ordering = ["id"]


class StudentForm(FormsForm):
    teacher_id = forms.ModelChoiceField(
        queryset=Teacher.objects.order_by("teacher_accounts_id"),
        empty_label=_("Choose Teacher"),
    )

    class Meta:
        verbose_name = _("Student Form")
        verbose_plural_name = _("Students Forms")
        model = Student
        fields = ["teacher_id", "first_name", "last_name", "middle_name", "age"]
        ordering = ["-id"]

    def clean_age(self):
        cleaned_data = super().clean()
        age = cleaned_data.get("age")

        if int(age) <= MAX_AGE_LIMIT:
            raise forms.ValidationError(
                _("Age of %(age)s is not allowde to use"),
                params={"age": age},
            )
        return age

grados/app/class/views.py
from django.shortcuts import render

# Create your views here.

grados/app/views/accounts.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from grados.app.accounts.models import CustomUser
from grados.app.forms.form import CustomAuthenticationForm


class AccountTemplateView(LoginView):
    template_name = "accounts/login.html"
    authentication_form = CustomAuthenticationForm


class AccountLogoutView(LoginRequiredMixin, LogoutView):
    template_name = "accounts/logout.html"
    login_url = reverse_lazy("accounts:accounts_login")
    redirect_field_name = "next_link"


class DashboardTemplateView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("accounts:accounts_login")
    template_name = "accounts/dashboard.html"
    redirect_field_name = "next_link"

grados/app/views/parents.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from grados.app.forms.form import ParentForms
from grados.app.mixin.messagemixin import MessageMixins
from grados.app.parents.models import Parent

# TODO: Name standard for the template names for CRUD functionality


class ParentTemplateView(MessageMixins, TemplateView):
    template_name = "parents/index.html"


class ParentCreateView(MessageMixins, CreateView):
    template_name = "parents/add_parent.html"
    form_class = ParentForms
    success_url = reverse_lazy("parents:parent_index")

grados/app/views/students.py
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, TemplateView

# TODO: make this standard importing for forms
from grados.app.forms.form import StudentForm
from grados.app.mixin.messagemixin import MessageMixins
from grados.app.students.models import Student


class StudentsTemplateView(TemplateView):
    template_name = "students/index.html"


# TODO: add the student urls
class StudentCreateView(MessageMixins, CreateView):
    template_name = "students/student_add.html"
    form_class = StudentForm
    message = "added"
    success_url = reverse_lazy("student:students_index")

grados/app/views/teachers.py
from django.contrib.auth import views
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from grados.app.forms.form import TeacherForms
from grados.app.mixin.messagemixin import MessageMixins
from grados.app.teachers.models import Teacher


class TeachersTemplateView(MessageMixins, TemplateView):
    template_name = "teachers/index.html"


class TeacherCreateView(MessageMixins, CreateView):
    template_name = "teachers/add_teacher.html"
    form_class = TeacherForms
    messages = "added"
    success_url = reverse_lazy("teachers:teachers_add")  # redirect and show messages

    # save the current logged-in user to the teacher model instance
    def form_valid(self, form):
        form.instance.teacher_accounts_id = self.request.user
        return super().form_valid(form)


class TeacherUpdateView(MessageMixins, UpdateView):
    pass

grados/templates/common/base.html
{% load static %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}| Grados</title>
    <!-- <link rel="stylesheet" href="{% static 'index.css' %}"> -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
		{% block navbar %} {% endblock navbar %}
    <div class="container-fluid" style="padding-left:0">
         {% block sidebar %}{% endblock sidebar %}
       <div class="login-form">
        {% block login_form %} {% endblock login_form %}
    </div>
	
    {% block content %}{% endblock content %}
    {% block logout_hero %}{% endblock logout_hero %}
    {% block indevelopment %}{% endblock indevelopment %}
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

grados/templates/common/error.html
{% if form.errors %}
 <!-- {% for field in form %} 
     {% for error in field.errors %} 
         <div class="alert alert-danger">
            <strong class="has-text-danger">{{ form.errors}}</strong>
        </div>  
     {% endfor %} 
 {% endfor %}  -->
 {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong class="has-text-danger">{{ error|escape }}</strong>
    </div>
{% endfor %}
 {% endif %} 

grados/templates/common/forms.html
{% load django_bootstrap5 i18n %}    
<form action ="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-success btn-md" type="submit">{% trans "Save" %}</button>
        <button class="btn btn-danger btn-md" type="submit">{% trans "Cancel" %}</button>
</form>

grados/templates/common/indevelopment.html
{% load i18n %}
<div class="px-4 py-5 my-5 text-center">
	<i class="fa-solid fa-triangle-exclamation fa-2xl" style="color: #ff7800;"></i>
    <h1 class="display-3 fw-bold">{% trans "This page is In-Development" %}</h1>
    <h3 class="display-6 fw-bold">{% trans "Developers still working on it" %} </h3>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">{% trans "Thank you again for using Grado Grading and Notification System. We are grateful for your time and look forward to continuing to use it in the future." %}</p>
    </div>
  </div>

grados/templates/common/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <i class="fa-solid fa-circle-info"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}

grados/templates/common/navbar.html
{% load i18n %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{% trans "Grado System" %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">{% trans "Home" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">{% trans "About" %}</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Services
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'teachers:teachers_index' %}">{% trans "Teachers" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'teachers:teachers_add' %}">{% trans "Teachers Info" %}</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Other Services</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">{% trans "Contact" %}</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
				<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-user"></i></a>
				<ul class="dropdown-menu aria-labelledby="profileDropdown">
				<li>
              <a class="nav-link" href="{% url 'accounts:accounts_logout' %}">{% trans "Logout" %}</a>
			   </li>
				<li>
              <a class="nav-link" href="{% url 'accounts:accounts_logout' %}">{% trans "Profile" %}</a>
			   </li>
				<li>
              <a class="nav-link" href="{% url 'accounts:accounts_logout' %}">{% trans "Settings" %}</a>
			   </li>
			 </ul>
				</li>
          </ul>
		  </ul>
      </div>
    </div>
  </nav>

grados/templates/common/sidebar.html
{% load i18n %}
<div class="container-fluid">
  <div class="row flex-nowrap">
      <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
          <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
              <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                  <span class="fs-5 d-none d-sm-inline">{% trans "Grado System" %}</span>
              </a>
              <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                  <li class="nav-item">
                      <a href="#" class="nav-link align-middle px-0">
                          <i class="fa-solid fa-house"></i> <span class="ms-1 d-none d-sm-inline">{% trans "Home" %}</span>
                      </a>
                  </li>
                  <li>
                      <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                        <i class="fa-solid fa-gauge"></i><span class="ms-1 d-none d-sm-inline">{% trans "Dashboard" %}</span> </a>
                      <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                          <li class="w-100">
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>
                          </li>
                          <li>
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
                          </li>
                      </ul>
                  </li>
                  <li>
                      <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                          <i class="fa-solid fa-paperclip"></i> <span class="ms-1 d-none d-sm-inline">{% trans "Miscellaneous" %}</span></a>
                      <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                          <li class="w-100">
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                          </li>
                          <li>
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                          </li>
                      </ul>
                  </li>
                  <li>
                      <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                          <i class="fa-solid fa-chalkboard-user"></i> <span class="ms-1 d-none d-sm-inline">{% trans "Teachers" %} </a>
                          <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                          <li class="w-100">
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">{% trans "Module" %}</a>
                          </li>
                          <li>
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">{% trans "Class" %} </a>
                          </li>
                          <li>
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">{% trans "Students Grades" %} </a>
                          </li>
                          <li>
                              <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">{% trans "Schedules" %} </a>
                          </li>
                      </ul>
                  </li>
              </ul>
              <hr>
              <div class="dropdown pb-4">
                  <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                      <span class="d-none d-sm-inline mx-1">loser</span>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                      <li><a class="dropdown-item" href="#">{% trans "Settings" %}</a></li>
                      <li><a class="dropdown-item" href="{% url 'teachers:teachers_add' %}">{% trans "Profile" %}</a></li>
                      <li>
                          <hr class="dropdown-divider">
                      </li>
                      <li><a class="dropdown-item" href="{% url 'accounts:accounts_logout' %}">{% trans "Logout" %}</a></li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="col py-3">
            {% include 'common/message.html' %}
          <div class="card bg-light">
              <div class="card-body">
                {% include 'common/forms.html' %}
          </div>
      </div>
      </div>
  </div>
</div>